import 'package:app_ui/theme/app_palette.dart';
import 'package:flutter/material.dart';

abstract final class AppColorScheme {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: AppPalette.blue,
    onPrimary: AppPalette.white,
    primaryContainer: AppPalette.blueSoft,
    onPrimaryContainer: AppPalette.blueDark,
    secondary: AppPalette.apricot,
    onSecondary: AppPalette.white,
    secondaryContainer: AppPalette.apricotSoft,
    onSecondaryContainer: AppPalette.ink,
    tertiary: AppPalette.apricot,
    onTertiary: AppPalette.white,
    tertiaryContainer: AppPalette.apricotSoft,
    onTertiaryContainer: AppPalette.ink,
    error: AppPalette.error,
    onError: AppPalette.white,
    errorContainer: Color(0xFFF9E2DF),
    onErrorContainer: Color(0xFF6F2721),
    surface: AppPalette.paper,
    onSurface: AppPalette.ink,
    onSurfaceVariant: AppPalette.slate,
    outline: Color(0xFFBEC9C5),
    outlineVariant: Color(0xFFD6DEDA),
    shadow: Color(0x1A0F172A),
    scrim: Color(0x660F172A),
    inverseSurface: AppPalette.ink,
    onInverseSurface: AppPalette.white,
    inversePrimary: AppPalette.blueSoft,
    surfaceContainerHighest: Color(0xFFEFEBE2),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AppPalette.blueGlow,
    onPrimary: AppPalette.night,
    primaryContainer: Color(0xFF1C3A35),
    onPrimaryContainer: Color(0xFFC7EAE0),
    secondary: Color(0xFFF1B38C),
    onSecondary: AppPalette.night,
    secondaryContainer: Color(0xFF553726),
    onSecondaryContainer: Color(0xFFFFE2CF),
    tertiary: Color(0xFFE9C87E),
    onTertiary: AppPalette.night,
    tertiaryContainer: Color(0xFF50421D),
    onTertiaryContainer: Color(0xFFFDE9B4),
    error: AppPalette.errorSoft,
    onError: AppPalette.night,
    errorContainer: Color(0xFF5B2B28),
    onErrorContainer: Color(0xFFF8D4D1),
    surface: AppPalette.night,
    onSurface: AppPalette.white,
    onSurfaceVariant: AppPalette.steel,
    outline: Color(0xFF425652),
    outlineVariant: Color(0xFF2B3A37),
    shadow: Color(0x66000000),
    scrim: Color(0x99000000),
    inverseSurface: AppPalette.white,
    onInverseSurface: AppPalette.night,
    inversePrimary: AppPalette.blueDark,
    surfaceContainerHighest: AppPalette.midnight,
  );
}
