name: infra_supabase
description: Infrastructure implementations backed by Supabase.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  supabase: ^2.10.2
  feature_auth:
    path: ../feature_auth
  feature_profile:
    path: ../feature_profile

dev_dependencies:
  build_runner: ^2.13.0
  injectable_generator: ^2.12.1
  lints: ^5.1.1
